const motos = [
  {
    id: 1,
    nombre: "CB500X",
    marca: "Honda",
    categoria: "Aventura",
    precio: 115000,
    tipo: "manual",
    foto: "https://example.com/images/honda_cb500x.jpg",
  },
  {
    id: 2,
    nombre: "MT-07",
    marca: "Yamaha",
    categoria: "Naked",
    precio: 120000,
    tipo: "manual",
    foto: "https://example.com/images/yamaha_mt07.jpg",
  },
  {
    id: 3,
    nombre: "Ninja 400",
    marca: "Kawasaki",
    categoria: "Deportiva",
    precio: 105000,
    tipo: "manual",
    foto: "https://example.com/images/kawasaki_ninja400.jpg",
  },
  {
    id: 4,
    nombre: "Duke 390",
    marca: "KTM",
    categoria: "Naked",
    precio: 98000,
    tipo: "manual",
    foto: "https://example.com/images/ktm_duke390.jpg",
  },
  {
    id: 5,
    nombre: "G 310 GS",
    marca: "BMW",
    categoria: "Aventura",
    precio: 95000,
    tipo: "manual",
    foto: "https://example.com/images/bmw_g310gs.jpg",
  },
  {
    id: 6,
    nombre: "PCX 160",
    marca: "Honda",
    categoria: "Scooter",
    precio: 65000,
    tipo: "automatica",
    foto: "https://example.com/images/honda_pcx160.jpg",
  },
  {
    id: 7,
    nombre: "Forza 300",
    marca: "Honda",
    categoria: "Scooter",
    precio: 105000,
    tipo: "automatica",
    foto: "https://example.com/images/honda_forza300.jpg",
  },
  {
    id: 8,
    nombre: "GSX-S750",
    marca: "Suzuki",
    categoria: "Naked",
    precio: 130000,
    tipo: "manual",
    foto: "https://example.com/images/suzuki_gsx-s750.jpg",
  },
  {
    id: 9,
    nombre: "Iron 883",
    marca: "Harley-Davidson",
    categoria: "Cruiser",
    precio: 150000,
    tipo: "manual",
    foto: "https://example.com/images/harley_iron883.jpg",
  },
  {
    id: 10,
    nombre: "Africa Twin",
    marca: "Honda",
    categoria: "Aventura",
    precio: 160000,
    tipo: "manual",
    foto: "https://example.com/images/honda_africa_twin.jpg",
  },
  {
    id: 11,
    nombre: "XMax 250",
    marca: "Yamaha",
    categoria: "Scooter",
    precio: 70000,
    tipo: "automatica",
    foto: "https://example.com/images/yamaha_xmax250.jpg",
  },
  {
    id: 12,
    nombre: "V-Strom 650",
    marca: "Suzuki",
    categoria: "Aventura",
    precio: 135000,
    tipo: "manual",
    foto: "https://example.com/images/suzuki_vstrom650.jpg",
  },
  {
    id: 13,
    nombre: "Burgman 400",
    marca: "Suzuki",
    categoria: "Scooter",
    precio: 110000,
    tipo: "automatica",
    foto: "https://example.com/images/suzuki_burgman400.jpg",
  },
  {
    id: 14,
    nombre: "R3",
    marca: "Yamaha",
    categoria: "Deportiva",
    precio: 97000,
    tipo: "manual",
    foto: "https://example.com/images/yamaha_r3.jpg",
  },
  {
    id: 15,
    nombre: "Meteor 350",
    marca: "Royal Enfield",
    categoria: "Cruiser",
    precio: 85000,
    tipo: "manual",
    foto: "https://example.com/images/royal_enfield_meteor350.jpg",
  },
  {
    id: 16,
    nombre: "CRF300L",
    marca: "Honda",
    categoria: "Off-road",
    precio: 90000,
    tipo: "manual",
    foto: "https://example.com/images/honda_crf300l.jpg",
  },
  {
    id: 17,
    nombre: "Tracer 900",
    marca: "Yamaha",
    categoria: "Aventura",
    precio: 140000,
    tipo: "manual",
    foto: "https://example.com/images/yamaha_tracer900.jpg",
  },
  {
    id: 18,
    nombre: "Vespa Primavera",
    marca: "Piaggio",
    categoria: "Scooter",
    precio: 72000,
    tipo: "automatica",
    foto: "https://example.com/images/piaggio_vespa_primavera.jpg",
  },
  {
    id: 19,
    nombre: "SR400",
    marca: "Yamaha",
    categoria: "Retro",
    precio: 85000,
    tipo: "semiautomatica",
    foto: "https://example.com/images/yamaha_sr400.jpg",
  },
  {
    id: 20,
    nombre: "Street Triple",
    marca: "Triumph",
    categoria: "Naked",
    precio: 155000,
    tipo: "manual",
    foto: "https://example.com/images/triumph_street_triple.jpg",
  },
  {
    id: 21,
    nombre: "Scoopy SH125i",
    marca: "Honda",
    categoria: "Scooter",
    precio: 62000,
    tipo: "automatica",
    foto: "https://example.com/images/honda_scoopy.jpg",
  },
  {
    id: 22,
    nombre: "Bonneville T100",
    marca: "Triumph",
    categoria: "Retro",
    precio: 145000,
    tipo: "manual",
    foto: "https://example.com/images/triumph_bonneville.jpg",
  },
  {
    id: 23,
    nombre: "Interceptor 650",
    marca: "Royal Enfield",
    categoria: "Retro",
    precio: 95000,
    tipo: "manual",
    foto: "https://example.com/images/royal_enfield_interceptor.jpg",
  },
  {
    id: 24,
    nombre: "Diavel 1260",
    marca: "Ducati",
    categoria: "Cruiser",
    precio: 175000,
    tipo: "manual",
    foto: "https://example.com/images/ducati_diavel.jpg",
  },
  {
    id: 25,
    nombre: "Panigale V2",
    marca: "Ducati",
    categoria: "Deportiva",
    precio: 200000,
    tipo: "manual",
    foto: "https://example.com/images/ducati_panigale.jpg",
  },
  {
    id: 26,
    nombre: "Himalayan",
    marca: "Royal Enfield",
    categoria: "Aventura",
    precio: 89000,
    tipo: "manual",
    foto: "https://example.com/images/royal_enfield_himalayan.jpg",
  },
  {
    id: 27,
    nombre: "Super Soco TC",
    marca: "Super Soco",
    categoria: "Electrica",
    precio: 68000,
    tipo: "automatica",
    foto: "https://example.com/images/super_soco_tc.jpg",
  },
  {
    id: 28,
    nombre: "LiveWire",
    marca: "Harley-Davidson",
    categoria: "Electrica",
    precio: 220000,
    tipo: "automatica",
    foto: "https://example.com/images/harley_livewire.jpg",
  },
  {
    id: 29,
    nombre: "Benelli TRK 502",
    marca: "Benelli",
    categoria: "Aventura",
    precio: 115000,
    tipo: "manual",
    foto: "https://example.com/images/benelli_trk502.jpg",
  },
  {
    id: 30,
    nombre: "CB300R",
    marca: "Honda",
    categoria: "Naked",
    precio: 85000,
    tipo: "manual",
    foto: "https://example.com/images/honda_cb300r.jpg",
  },
  {
    id: 31,
    nombre: "R 1250 GS",
    marca: "BMW",
    categoria: "Aventura",
    precio: 180000,
    tipo: "manual",
    foto: "https://example.com/images/bmw_r1250gs.jpg",
  },
  {
    id: 32,
    nombre: "Super Cub C125",
    marca: "Honda",
    categoria: "Scooter",
    precio: 70000,
    tipo: "semiautomatica",
    foto: "https://example.com/images/honda_supercub.jpg",
  },
  {
    id: 33,
    nombre: "Street Rod",
    marca: "Harley-Davidson",
    categoria: "Cruiser",
    precio: 130000,
    tipo: "manual",
    foto: "https://example.com/images/harley_streetrod.jpg",
  },
  {
    id: 34,
    nombre: "Gixxer SF 250",
    marca: "Suzuki",
    categoria: "Deportiva",
    precio: 85000,
    tipo: "manual",
    foto: "https://example.com/images/suzuki_gixxer.jpg",
  },
  {
    id: 35,
    nombre: "CBR650R",
    marca: "Honda",
    categoria: "Deportiva",
    precio: 150000,
    tipo: "manual",
    foto: "https://example.com/images/honda_cbr650r.jpg",
  },
  {
    id: 36,
    nombre: "XPulse 200",
    marca: "Hero",
    categoria: "Aventura",
    precio: 70000,
    tipo: "manual",
    foto: "https://example.com/images/hero_xpulse200.jpg",
  },
  {
    id: 37,
    nombre: "Rebel 300",
    marca: "Honda",
    categoria: "Cruiser",
    precio: 93000,
    tipo: "manual",
    foto: "https://example.com/images/honda_rebel300.jpg",
  },
  {
    id: 38,
    nombre: "Hyperstrada 939",
    marca: "Ducati",
    categoria: "Aventura",
    precio: 165000,
    tipo: "manual",
    foto: "https://example.com/images/ducati_hyperstrada.jpg",
  },
  {
    id: 39,
    nombre: "CBR1000RR",
    marca: "Honda",
    categoria: "Deportiva",
    precio: 190000,
    tipo: "manual",
    foto: "https://example.com/images/honda_cbr1000rr.jpg",
  },
  {
    id: 40,
    nombre: "Bullet 500",
    marca: "Royal Enfield",
    categoria: "Retro",
    precio: 80000,
    tipo: "semiautomatica",
    foto: "https://example.com/images/royal_enfield_bullet500.jpg",
  },
];
